const data = [
        { id: "1", name: "Explorer", price: 2000, description: "The Explorer is a bike    designed to get you out of the house and into nature. The idea is that you can pack up your home and escape for a weekend or even longer!", imageUrl: "../public/auto/bike.jpeg", type: "Land", hostId: 115 },
        { id: "2", name: "Roadster", price: 6000, description: "Roadster is an iconic luxury SUV known for its rugged off-road capabilities, premium features, and distinctive boxy design. its exceptional off-road capabilities, with advanced four-wheel-drive systems, high ground clearance, and durable construction.", imageUrl: "../public/auto/car.avif", type: "Land", hostId: 111 },
        { id: "3", name: "Beach Bum", price: 5500, description: "Beach Bum is a van inspired by surfers and travelers. It was created to be a portable home away from home, but with some cool features in it you won't find in an ordinary camper. There's a small kitchen, so you can cook if you need to. You'll feel like home as soon as you step out of it.", imageUrl: "../public/auto/jeep.jpeg", type: "Land", hostId: 115 },
        { id: "4", name: "Dreamfinder", price: 4000, description: "Dreamfinder is the perfect van to travel in and experience. With a ceiling height of 2.1m, you can stand up in this van and there is great head room. The floor is a beautiful glass-reinforced plastic (GRP) which is easy to clean and very hard wearing. A large rear window and large side windows make it really light inside and keep it well ventilated.", imageUrl: "../public/auto/van.jpeg", type: "Land", hostId: 115 },
        { id: "5", name: "The Cruiser", price: "1M", description: "The Cruiser is a yacht for those who love to travel in comfort and luxury. With its many windows, spacious interior and ample storage space, the Cruiser offers a beautiful view wherever you go.", imageUrl: "../public/auto/yacht.jpeg", type: "Water", hostId: 111 },
        { id: "6", name: "Wanderer", price: 3000, description: "Wanderer is a small vessel propelled by a jet of water expelled from the back of the craft. It offers an exciting and adrenaline-filled experience on the water, allowing riders to explore waterways, enjoy the thrill of speed, and connect with the natural beauty of their surroundings.", imageUrl: "../public/auto/ski.webp", type: "Water", hostId: 115 },
        { id: "7", name: "Rover", price: 1000, description: "Rover is designed to be manually operated by one or more paddlers who sit facing forward. It is a versatile and accessible outdoor activity that offers opportunities for adventure, exercise, and exploration. Whether paddling calm waters or navigating challenging rapids, kayakers can experience the beauty of nature and the thrill of adventure from the unique vantage point of their kayak.", imageUrl: "../public/auto/kayak.jpeg", type: "Water", hostId: 111 },
        { id: "8", name: "Aqua Titan", price: 7550, description: "Whether for leisure or business, boats offer a means of experiencing the natural beauty of lakes, rivers, oceans, and coastal regions while providing opportunities for adventure and relaxation.  It offers opportunities for fishing, water sports, cruising, sightseeing, and socializing with friends and family.", imageUrl: "../public/auto/boat.webp", type: "Water", hostId: 111 },
        { id: "9", name: "Modest Explorer", price: "50K", description: "The vertical flight capabilities that enable to perform a wide range of missions across diverse sectors. As a versatile platform for transportation, aerial work, and specialized operations, explorer provide essential services and support critical missions.", imageUrl: "../public/auto/helicopter.webp", type: "Air", hostId: 111 },
        { id: "10", name: "Wright Wonder", price: "100K", description: "With this vehicle, you can take your travel life to the next level. The Green Wonder is a sustainable vehicle that's perfect for people who are looking for a stylish, eco-friendly mode of transport that can go anywhere.", imageUrl: "../public/auto/plane.webp", type: "Air", hostId: 119 },
        { id: "11", name: "Sky Stromer", price: "70K", description: "Stromer offers a luxurious and exclusive mode of air travel tailored to the needs and preferences of discerning travelers. With their range, comfort, and flexibility, private jets provide a convenient and prestigious means of transportation for those who value privacy, convenience, and personalized service.", imageUrl: "../public/auto/jet.webp", type: "Air", hostId: 111 }]

export default data

/// 111, 115, 119